### ISSUE TITLE
broader support for get queries

### ISSUE THREAD

**Issue by laroque** [project8/mantis#48] opened 2015-05-31 02:43 UTC
If I try to "get" components of the configuration (mantis.duration or mantis.devices.<some_valid_name>.enabled); the result is `return-msg : Unrecognized query type or no query type provided`.

I'm not sure if this is a bug report or a feature request. If the latter, it is the duration in particular that I'm interested in. The dripline interface uses its logging functionality to send "run" commands at a regular interval and effectively take data continuously. For that to be timed correctly, I'd like to be able to query the run duration that is currently set and log at that interval. We can, of course, approximate actively setting both each time, but it seems like something that should just be set in server's config file and then read from then on.

**Comment by nsoblath** [comment] 2015-05-31 22:06
This should be pretty easy to implement. I'll make it an extension of the 'get' command with the 'acq-config' target.

**Comment by nsoblath** [comment] 2015-05-31 22:12
On second thought, the command structure should parallel that of the set commmand. If the target isn't recognized as a specific command, it'll be assumed to be a config setting.

**Comment by laroque** [comment] 2015-05-31 22:37
That's what I tried, something like: `mantis_client do=get dest=mantis.devices.pxie1.enabled`

**Comment by nsoblath** [comment] 2015-09-22 16:25
Closed as a partial duplicate of #54.

**Closed by nsoblath** 2015-09-22 16:25 UTC
Labels: Feature Request
